export const aromePiServer = "https://public-api.meteofrance.fr/public/aromepi/1.0";

export const aromePiParams = {
  WIND_SPEED_GUST__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND: "WIND",
  WIND_SPEED_GUST_15MIN__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND: "WIND_15MIN",
  WIND_SPEED_MAXIMUM_GUST__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND: "WIND_MAX",
  U_COMPONENT_OF_WIND_GUST_15MIN__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND: "U_WIND_15MIN",
  U_COMPONENT_OF_WIND_GUST__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND: "U_WIND",
  V_COMPONENT_OF_WIND_GUST_15MIN__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND: "V_WIND_15MIN",
  V_COMPONENT_OF_WIND_GUST__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND: "V_WIND",

  // Quantité totale de précipitations.
  TOTAL_PRECIPITATION__GROUND_OR_WATER_SURFACE: "PRECIPITATION",

  PRECIPITATION_TYPE_15_MIN__GROUND_OR_WATER_SURFACE: "PRECIPITATION_15MIN",

  // Type de précipitation le plus sévère sur 15 minutes
  SEVERE_PRECIPITATION_TYPE_15_MIN__GROUND_OR_WATER_SURFACE: "SEVERE_PRECIPITATION_15MIN",

  // Quantité de précipitations solides
  SOLID_PRECIPITATION__GROUND_OR_WATER_SURFACE: "PRECIPITATION_SOLID",

  // Intensité des précipitations
  TOTAL_PRECIPITATION_RATE__GROUND_OR_WATER_SURFACE: "PRECIPITATION_RATE",

  // Diagnostic de pluie sur sol gelé
  PRECIPITATION_FZN_GROUND__GROUND_OR_WATER_SUFACE: "PRECIPITATION_FZN",

  REFLECTIVITY_MAX_DBZ__GROUND_OR_WATER_SURFACE: "REFLECTIVITY",
};

export const aromePiGrids = {
  "MF-NWP-HIGHRES-AROMEPI-001-FRANCE-WCS": "AROMEPI-001",
  "MF-NWP-HIGHRES-AROMEPI-0025-FRANCE-WCS": "AROMEPI-0025",
};
