export const aromePiServer = "https://public-api.meteofrance.fr/public/aromepi/1.0";

export const aromePiParams = {
  WIND_SPEED_GUST__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND: "WIND",
  WIND_SPEED_GUST_15MIN__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND: "WIND_15MIN",
  WIND_SPEED_MAXIMUM_GUST__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND: "WIND_MAX",
  U_COMPONENT_OF_WIND_GUST_15MIN__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND: "U_WIND_15MIN",
  U_COMPONENT_OF_WIND_GUST__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND: "U_WIND",
  V_COMPONENT_OF_WIND_GUST_15MIN__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND: "V_WIND_15MIN",
  V_COMPONENT_OF_WIND_GUST__SPECIFIC_HEIGHT_LEVEL_ABOVE_GROUND: "V_WIND",
};

export const aromePiGrids = {
  "MF-NWP-HIGHRES-AROMEPI-001-FRANCE-WCS": "AROMEPI-001",
  "MF-NWP-HIGHRES-AROMEPI-0025-FRANCE-WCS": "AROMEPI-0025",
};
